package weightTrackerPojo;
// Generated Jan 18, 2018 2:53:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exercise generated by hbm2java
 */
public class Exercise  implements java.io.Serializable {


     private Integer exerciseId;
     private String exerciseType;
     private Integer exerciseDuration;
     private Integer calorieBurnt;
     private Set exercisedailylogs = new HashSet(0);

    public Exercise() {
    }

    public Exercise(String exerciseType, Integer exerciseDuration, Integer calorieBurnt, Set exercisedailylogs) {
       this.exerciseType = exerciseType;
       this.exerciseDuration = exerciseDuration;
       this.calorieBurnt = calorieBurnt;
       this.exercisedailylogs = exercisedailylogs;
    }
   
    public Integer getExerciseId() {
        return this.exerciseId;
    }
    
    public void setExerciseId(Integer exerciseId) {
        this.exerciseId = exerciseId;
    }
    public String getExerciseType() {
        return this.exerciseType;
    }
    
    public void setExerciseType(String exerciseType) {
        this.exerciseType = exerciseType;
    }
    public Integer getExerciseDuration() {
        return this.exerciseDuration;
    }
    
    public void setExerciseDuration(Integer exerciseDuration) {
        this.exerciseDuration = exerciseDuration;
    }
    public Integer getCalorieBurnt() {
        return this.calorieBurnt;
    }
    
    public void setCalorieBurnt(Integer calorieBurnt) {
        this.calorieBurnt = calorieBurnt;
    }
    public Set getExercisedailylogs() {
        return this.exercisedailylogs;
    }
    
    public void setExercisedailylogs(Set exercisedailylogs) {
        this.exercisedailylogs = exercisedailylogs;
    }




}


