package weightTrackerPojo;
// Generated Jan 18, 2018 2:53:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Meal generated by hbm2java
 */
public class Meal  implements java.io.Serializable {


     private Integer mealId;
     private String mealName;
     private Double calorieValue;
     private Float mealUnit;
     private Set mealdailylogs = new HashSet(0);

    public Meal() {
    }

    public Meal(String mealName, Double calorieValue, Float mealUnit, Set mealdailylogs) {
       this.mealName = mealName;
       this.calorieValue = calorieValue;
       this.mealUnit = mealUnit;
       this.mealdailylogs = mealdailylogs;
    }
   
    public Integer getMealId() {
        return this.mealId;
    }
    
    public void setMealId(Integer mealId) {
        this.mealId = mealId;
    }
    public String getMealName() {
        return this.mealName;
    }
    
    public void setMealName(String mealName) {
        this.mealName = mealName;
    }
    public Double getCalorieValue() {
        return this.calorieValue;
    }
    
    public void setCalorieValue(Double calorieValue) {
        this.calorieValue = calorieValue;
    }
    public Float getMealUnit() {
        return this.mealUnit;
    }
    
    public void setMealUnit(Float mealUnit) {
        this.mealUnit = mealUnit;
    }
    public Set getMealdailylogs() {
        return this.mealdailylogs;
    }
    
    public void setMealdailylogs(Set mealdailylogs) {
        this.mealdailylogs = mealdailylogs;
    }




}


